### ISSUE TITLE
Dawntrail Update Checklist / Tracking

### ISSUE THREAD

**Issue by valarnin** [OverlayPlugin/OverlayPlugin#358]
This issue is meant to act as a general checklist of things to test, verify, and potentially PR fixes for after the Dawntrail release.

Pull requests for Dawntrail should reference this issue for tracking purposes.

For any struct changes, be those network packet structs or memory structs, make sure to create new structs for 7.0 so as to not break CN/KR support.

- [ ] Adjust for any changes in `Machina`
- [ ] Adjust for any changes in `FFXIV_ACT_Plugin.dll`
- [ ] Verify network packet updates for all possible packets
  - [ ] Verify packet layouts
  - [ ] Update and verify opcodes
  - Network packet code that needs to be verified lives under `OverlayPlugin.Core/NetworkProcessors`
  - [ ] `OverlayPlugin.Core/MemoryProcessors/LineCombatant.cs` reads the `ActorID` and `LoginUserID` values from the packet header. Verify that these don't need adjusted.
- [ ] Verify memory updates
  - [ ] Verify memory struct layouts
  - [ ] Verify memory signatures
  - Memory code that needs to be verified lives under `OverlayPlugin.Core/MemoryProcessors`
  - `AtkStage` can be ignored, as it is not currently in use

**Comment by valarnin** [comment]
I am looking into the broken signatures, currently:

Fixed but haven't PRd:
```
Error: Failed to find in combat memory via InCombatMemory61: inCombatAddress.
```

Investigating:
```
Error: Failed to find content finder settings memory via ContentFinderSettingsMemory651: settingsAddress.
Error: Failed to find target memory via TargetMemory63: targetAddress.
Error: Failed to find enmity HUD memory via EnmityHudMemory62: enmityHudAddress.
```

These errors belong to cactbot:
```
Error: Job signature found 0 matches
Error: In combat signature found 0 matches
```

**Comment by valarnin** [comment]
There are two outstanding issues:

1. Need to verify that we have the correct offset for `PCTargetID` in the `Combatant` struct
2. Need to review the `getCombatants` logic in its entirety and determine how to handle potential read-past-allocation-boundary issues (see Discord #beta-testing discussions)
